# tauv is the meridional component of wind stress
# eta0_sin is the amplitude of the sinusoidal initial surface perturbation
# applied to the model. Keep this set to 0 for most model runs

param_analytic = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 0,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 1,
              "t": 86400}

param_1day = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 0,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 1,
              "t": 86400}

param_50day = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 0,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 50,
              "t": 86400}

# Runs the model with a gridsize 50% smaller and adjusts the timestep size
# accordingly
param_50day_halfgrid = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 0,
              "dx": 1e4,
              "dy": 1e4,
              "dt": 58,
              "days": 50,
              "t": 86400}

# Initialises the model with a zonally sinusoidal surface perturbation of amplitude 0.3m
param_1day_sin03 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 0.3,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 1,
              "t": 86400}

param_30day_sin03 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 0.3,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 30,
              "t": 86400}

param_100day_sin03 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 0.3,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 100,
              "t": 86400}

# Initialises the model with a zonally sinusoidal surface perturbation of amplitude 1m
param_1day_sin1 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 1,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 1,
              "t": 86400}

param_30day_sin1 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 1,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 30,
              "t": 86400}

param_100day_sin1 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 0,
              "eta0": 0,
              "eta0_sin": 1,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 100,
              "t": 86400}

param_50day_stochastic = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 1,
              "eta0": 0,
              "eta0_sin": 0,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 120,
              "days": 50,
              "t": 86400}

param_1day_stochastic_sin1 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 1,
              "eta0": 0,
              "eta0_sin": 1,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 100,
              "days": 1,
              "t": 86400}

param_50day_stochastic_sin1 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 1,
              "eta0": 0,
              "eta0_sin": 1,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 100,
              "days": 50,
              "t": 86400}

param_100day_stochastic_sin1 = {"L": 1e6,
              "f0": 1e-4,
              "beta": 1e-11,
              "g": 10,
              "gamma": 1e-6,
              "rho": 1000,
              "H": 1000,
              "tau0": 0.2,
              "tauv": 1,
              "eta0": 0,
              "eta0_sin": 1,
              "dx": 2e4,
              "dy": 2e4,
              "dt": 100,
              "days": 100,
              "t": 86400}
